### ISSUE TITLE
Invalid status 403 for below code

### ISSUE THREAD

**Issue by anshudaur** [rhysd/node-github-trend#5]
Hi,

I am pretty sure the below code worked , but i am getting 403 error. Is there a limit to which i can call the api in a day?
Please help.
var http = require('http');
var Trending = require("github-trend");
//var scraper = new Trending.Scraper();
 var client = new Trending.Client();
// Empty string means 'all languages' 
client.fetchTrending("").then(function(repos){
    repos.forEach(function(repo){
        console.log(repo.owner+","+repo.name+","+repo.description+","+repo.language+","+repo.allStars);       
    });
}).catch(function(err){
    console.log(err.message);
});
 
client.requestDefaults = 'https://myproxy.com:8087';

http.createServer(function (req, res) {
	res.writeHead(200, {'Content-Type': 'text/plain'})
    res.end('');
  
}).listen(8087);

console.log('Server started on 8087');

**Comment by rhysd** [comment]
You mean you're using proxy server? I guess you should set `http_proxy` environment variable

**Comment by anshudaur** [comment]
i tried, but i am getting 
C:\Users\admin2\Trending\TrendingApp\index.js:18
client.requestDefaults.http_proxy = 'https://myproxy.com:8087';
                                  ^

TypeError: Cannot set property 'http_proxy' of undefined
    at Object.<anonymous> (C:\Users\admin2\Trending\TrendingApp\index.js:18:35)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:389:7)
    at startup (bootstrap_node.js:149:9)

**Comment by rhysd** [comment]
I said 'environment variable'. You should `export https_proxy="..."` in your shell.

**Comment by anshudaur** [comment]
I am sorry if i am wrong again, but i tried this to set http_proxy
npm config set https-proxy http://proxy_host:port -g

**Comment by anshudaur** [comment]
I also tried to execute the code after removing the line : 
client.requestDefaults = 'https://myproxy.com:8087';
I had the output earlier.

**Comment by rhysd** [comment]
it's config for npm itself and does not affect to your script.

I mean below

```
$ export https_proxy="https://myproxy.com:8087"
$ node your_script.js
```

**Comment by rhysd** [comment]
Please read doc of request.

https://github.com/request/request#controlling-proxy-behaviour-using-environment-variables

**Comment by anshudaur** [comment]
I tried that too, but i am still getting 403
I do not want to go with the proxy server now, as i just want to make the code work back to how it was. Seems like, i can't do that either.

**Comment by anshudaur** [comment]
Sorry, it worked !
[object Object],awesome-guidelines,A curated list of high quality coding style c
onventions and standards.,null,undefined
[object Object],Bash-Snippets,A collection of small bash scripts for heavy termi
nal users,Shell,undefined

I still have a question, i am getting stars value as undefined. 
Regarding getting owners, i can see author_url but  what should i do to get all the contributors ?

**Comment by anshudaur** [comment]
Hi Linda,
One quick question, is there a limit to number of requests that can be send
to your api?
Because i get 403 error even if i do not do any change in the existing code.
hope you don't mind my questions. :)

**Comment by rhysd** [comment]
> I still have a question, i am getting stars value as undefined.

This library scrapes GitHub's trending repository pages. So it may fail to get some attributes when GitHub updates the pages. We need to update this library following it. You can do it by sending PR. 

> One quick question, is there a limit to number of requests that can be send
to your api?

There is no limit because of scraping but too many accesses may cause error response from server.

**Comment by anshudaur** [comment]
Thanks  Linda :)

**Comment by anshudaur** [comment]
HI Linda,

I am still able to request data from your repository only twice in a hour. I wanted to know if there is anything that could be done to entertain more requests or if you know of any similar repositories?

Thanks for your reply.

Regards
Anshu

**Comment by rhysd** [comment]
> I am still able to request data from your repository only twice in a hour.

We can't know GitHub's internal server implementation. So I can say nothing.

> I wanted to know if there is anything that could be done to entertain more requests or if you know of any similar repositories?

As I said above, this is scraping library. So other than the information displayed in the page cannot be obtained.

**Comment by rhysd** [comment]
closing this due to no response
